### ISSUE TITLE
SSE float output

### ISSUE THREAD

**Issue by TbtBI** [dubhater/vapoursynth-sangnom#1]
Hi,
SSE float output has visible difference compared to SSE 8..16-bit / all C outputs (including float). Here an example - http://imgbox.com/g/9LlJteAI8l

**Comment by dubhater** [comment]
I found a problem in the float code. Can you compile it and test or do you need a binary?

**Comment by TbtBI** [comment]
The output is still quite different.
http://imgbox.com/g/3rHrOWNWfG - 8-bit_sse / 16-bit_sse / 32-bit_sse. The difference in the area of the bottom right is the most visible.
http://imgbox.com/g/cUermxpn1X - 8-bit_c / 16-bit_c / 32-bit_c.

Btw between 16-bit_sse and 16-bit_c there is no visible difference but between 8-bit_sse and 8-bit_c there are visible different pixels (clamping, rounding ?).

**Comment by dubhater** [comment]
That should fix it.

**Comment by TbtBI** [comment]
8-bit_sse has identincal output as [avs version](https://github.com/tp7/SangNom2). Now even for 8-bit (c code) the output is different than the avs plug. Unless there is a simd error in the avs version too?

**Comment by dubhater** [comment]
Found another bug, though I don't think it has to do with your problem.

**Comment by TbtBI** [comment]
Yes, still no change in the output.
Thanks for your time.
Should I close the issue or leave it as a reminder?

**Comment by dubhater** [comment]
I'll close it when it's fixed. I found two other bugs in the C code. Now the 8 bit output is the same. I'll push the fixes after I fix the 16 bit and float output too.

**Comment by dubhater** [comment]
Is it okay now?

**Comment by TbtBI** [comment]
It's better than before.
http://imgbox.com/g/rfGdwz8BqH - 8-bit / 16-bit / new float / old float. (the faucets in the bottom right area)

**Comment by dubhater** [comment]
It doesn't look quite right, but I don't want to look at this code anymore.

Does it help if you change the division by 256 into a division by 255? https://github.com/dubhater/vapoursynth-sangnom/blob/788bc2d0fb7c102213e4d1cc63b9061d59e3b390/src/sangnom.cpp#L1730

**Comment by TbtBI** [comment]
There is no change in the output using 255 instead of 256.

Edit: Btw now both float C and SSE have the same output.
